version: '3'

services:
  ps-database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/posgresql/data
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: db_user
      POSTGRES_DB: node_app_db

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    environment:
      PORT: 7000
      NODE_ENV: production
      LOG_FILE_NAME: server.log

      DATABASE_HOST: ps-database
      DATABASE_USERNAME: db_user
      DATABASE_PASSWORD: db_password
      DATABASE_NAME: node_app_db
      DATABASE_PORT: 5432

      REDIS_HOST: redis
    depends_on:
      - redis
      - ps-database
    ports:
      - 7000:7000
    command:
      - /bin/bash
      - -c
      - |
        npm run migration:run
        npm run start
    labels:
      kompose.service.type: LoadBalancer

volumes:
  db-data:
